server:
  servlet:
    context-path: /api
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eCommerce
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

product:
  url: http://challenge-api.luizalabs.com/api/product